### ISSUE TITLE
データ行列Aの項目数の変化

### ISSUE THREAD

**Issue by ot7016** [ot7016/PCoordAGI#16]

**Comment by ot7016** [comment]
MDSでやってたときはデータを格納してある行列Aの行数が(項目数+属性数)となっており、元々のデータに属性の軸を表す単位行列を追加していた。
PCAにする場合にはこれを行う必要がなくなる。
これに伴い主にAGIのコード全般に修正が必要
MDSで計算する機能も残しておきたいのでそのあたりも考慮

**Comment by ot7016** [comment]
MDSとPCA、双方の計算結果の入力に対応

**Comment by wakita** [comment]
PCAのときも軸は表示するとよいと思うんですが，対応しているんですか？
