### ISSUE TITLE
ファイルを開く

### ISSUE THREAD

**Issue by ot7016** [ot7016/PCoordAGI#17]
ファイルを開いた場合今までのデータを全て書き換える必要あり
一部Paneも作り直す必要あり(PCPなど)
今は最初の一回のみ読み込む前提なのでコードを大幅に書き換えなければならない可能性がある

**Comment by wakita** [comment]
「大幅に変更」というのはよろしくありませんね。Social Viewpoint Finderでは、データセット名をディレクトリ名として、その下のファイルは統一形式にしました。たとえば、karate の場合は以下のような感じです。
- karate
  - centrality
    - Betweenness.bin
    - Closeness.bin
    - ClusteringCoefficent.bin
    - Degree.bin
    - PageRank.bin
  - graph
    - distance.bin
    - graph.bin
  - layout
    - eigenalues.bin
    - layout-hd.bin
  - profile
    time.txt
  - profile.dat

で、どこかに data/ というディレクトリを用意して、そのなかに karate, mathematica, uspoll, ... のようにデータセットを配置しています。c++ の readdir で data directory を探って、そこにあるすべてのデータセット名をすべてを一気に Dataset メニューに登録してしまい、メニュー項目を選ぶだけでデータセットを切り替えられると便利じゃないでしょうか。データセットが増えても、プログラムの修正がいりませんし、データセットを管理するためのややこしい仕掛けもいらないので。単に、 pcoordagi ../../data みたいにデータセット集のディレクトリだけ指定して起動すればいいと思います。

**Comment by ot7016** [comment]
再読み込みしてPaneを作り直す際に画面下のMatrixViewの部分だけがうまくいかない
すべて重なって表示されてしまう

**Comment by ot7016** [comment]
重なって表示される問題解消
Layout関数を呼び出せばOK
