### ISSUE TITLE
AGIからPCPへの反映

### ISSUE THREAD

**Issue by ot7016** [ot7016/PCoordAGI#3]
射影を利用して PCPの表示変更

**Comment by ot7016** [comment]
まずは簡単に実装を行う

**Comment by ot7016** [comment]
ノードをクリックすると落ちる不具合は解決　実装ミスで0での除算が発生していた

**Comment by ot7016** [comment]
ただ現在PCP部分が表示されない

**Comment by wakita** [comment]
/0 割り算のデバッグは念力デバッグですか？もし，そうだったら次回は gdb を使ってみてください．一発でどの行でこけているか見えますから．

**Comment by ot7016** [comment]
ほぼ完了
今の方法でよいのかは検討の必要あり
